import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { JSDOM } from 'jsdom';
import { fixture } from './storage-fixture.js';
import { STORAGE_KEY } from '../store.js';

test('manager renders, searches, creates, and moves bookmarks through the API', async () => {
  const dom = new JSDOM(await readFile(new URL('../manager.html', import.meta.url), 'utf8'), { url: 'https://extension.local/manager.html' });
  globalThis.document = dom.window.document;
  globalThis.DOMParser = dom.window.DOMParser;
  const $ = id => document.getElementById(id);
  dom.window.HTMLDialogElement.prototype.showModal = function () { this.setAttribute('open', ''); };
  dom.window.HTMLDialogElement.prototype.close = function () { this.removeAttribute('open'); this.dispatchEvent(new dom.window.Event('close')); };
  const root = { id: 'root________', children: [{ id: 'toolbar_____', parentId: 'root________', title: 'Bookmarks Toolbar', children: [] }, { id: 'unfiled_____', parentId: 'root________', title: 'Other Bookmarks', children: [{ id: 'a', parentId: 'unfiled_____', title: '<img onerror=alert(1)>', url: 'https://example.com/', type: 'bookmark' }, { id: 'folder', parentId: 'unfiled_____', title: 'Reading', children: [] }] }] };
  const mock = fixture(root);
  globalThis.browser = mock.api;
  Object.defineProperty(globalThis.navigator, 'locks', { value: mock.locks, configurable: true });
  await import('../manager.js');
  const settle = () => new Promise(resolve => setTimeout(resolve, 10));
  await settle();
  assert.equal($('items').children.length, 1);
  assert.equal($('items').querySelector('img'), null, 'bookmark names are rendered as text');
  $('gallery-view').click();
  assert.equal(document.querySelector('.table-wrap').classList.contains('gallery'), true);
  assert.equal($('gallery-view').getAttribute('aria-pressed'), 'true');
  assert.equal($('items').querySelector('.card-preview').textContent, 'No preview');
  $('list-view').click();
  assert.equal(document.querySelector('.table-wrap').classList.contains('gallery'), false);
  $('search').value = 'Reading'; $('search').dispatchEvent(new dom.window.Event('input'));
  await new Promise(resolve => setTimeout(resolve, 150));
  assert.equal($('items').children.length, 1);
  assert.equal($('items').querySelector('.item-title').textContent, 'Reading');
  $('all-bookmarks').click(); $('new-bookmark').click();
  $('edit-name').value = 'New bookmark'; $('edit-url').value = 'https://mozilla.org/';
  $('editor-form').dispatchEvent(new dom.window.SubmitEvent('submit', { cancelable: true, submitter: $('editor-form').querySelector('[type=submit]') }));
  await settle();
  assert.equal($('items').children.length, 2);
  $('select-all').click(); $('move-selected').click(); $('move-parent').value = 'folder';
  $('move-form').dispatchEvent(new dom.window.SubmitEvent('submit', { cancelable: true, submitter: $('move-form').querySelector('[type=submit]') }));
  await settle();
  const saved = (await browser.storage.local.get(STORAGE_KEY))[STORAGE_KEY].root;
  assert.equal(saved.children[1].children.find(n => n.id === 'folder').children.length, 2);
  assert.equal(root.children[1].children.length, 2, 'Firefox collection is unchanged');
  assert.equal(root.children[1].children[1].children.length, 0);
  assert.equal(mock.reads(), 1);
  // The status toast expires after six seconds; leave the document alive
  // until the module's pending timer has completed.
  await new Promise(resolve => setTimeout(resolve, 6100));
  dom.window.close();
});

test('Add to Marked suggests tags and saves the abstract, note, and tags; X posts embed only in the gallery', async () => {
  const pageURL = 'https://example.com/post';
  const dom = new JSDOM(await readFile(new URL('../manager.html', import.meta.url), 'utf8'), { url: `https://extension.local/manager.html?add=${encodeURIComponent(pageURL)}&title=${encodeURIComponent('Machine learning notes')}&capture=capture-1` });
  globalThis.document = dom.window.document;
  globalThis.DOMParser = dom.window.DOMParser;
  const $ = id => document.getElementById(id);
  dom.window.HTMLDialogElement.prototype.showModal = function () { this.setAttribute('open', ''); };
  dom.window.HTMLDialogElement.prototype.close = function () { this.removeAttribute('open'); this.dispatchEvent(new dom.window.Event('close')); };
  const mock = fixture({ id: 'root________', children: [{ id: 'unfiled_____', parentId: 'root________', title: 'Other Bookmarks', children: [] }] });
  const session = { 'capture-1': { url: pageURL, abstract: 'Agents that learn by imagining outcomes.', highlight: '  A key   passage. ', createdAt: Date.now() } };
  mock.api.storage.session = { get: async key => ({ [key]: session[key] }), remove: async key => { delete session[key]; } };
  globalThis.browser = mock.api;
  Object.defineProperty(globalThis.navigator, 'locks', { value: mock.locks, configurable: true });
  await import('../manager.js?add');
  const settle = () => new Promise(resolve => setTimeout(resolve, 10));
  const submit = () => $('editor-form').dispatchEvent(new dom.window.SubmitEvent('submit', { cancelable: true, submitter: $('editor-form').querySelector('[type=submit]') }));
  const chips = () => [...document.querySelectorAll('#edit-tags .tag-option')];
  const pressed = () => chips().filter(chip => chip.getAttribute('aria-pressed') === 'true').map(chip => chip.textContent);
  await settle();
  assert.ok($('editor').open);
  assert.equal($('edit-abstract').value, 'Agents that learn by imagining outcomes.');
  assert.deepEqual(session, {}, 'the capture is consumed');
  assert.deepEqual(pressed(), ['AI'], 'tags are suggested from the title');
  assert.match($('tags-hint').textContent, /Suggested .*AI/);
  chips().find(chip => chip.textContent === 'Technology').click();
  $('new-tag').value = 'Robotics';
  const enter = new dom.window.KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true });
  $('new-tag').dispatchEvent(enter);
  assert.equal(enter.defaultPrevented, true, 'Enter adds the tag instead of submitting');
  assert.deepEqual(pressed(), ['Technology', 'AI', 'Robotics']);
  assert.equal($('highlight-field').hidden, false, 'a highlight from the page is shown in the editor');
  assert.equal($('edit-highlight').textContent, 'A key passage.');
  $('edit-highlight-note').value = 'Why it matters';
  $('edit-note').value = '  Read before the meetup ';
  $('edit-abstract').value += ' Edited.';
  submit(); await settle();
  const saved = (await browser.storage.local.get(STORAGE_KEY))[STORAGE_KEY].root.children.find(node => node.url === pageURL);
  assert.equal(saved.abstract, 'Agents that learn by imagining outcomes. Edited.');
  assert.equal(saved.note, 'Read before the meetup');
  assert.deepEqual(saved.tags, ['AI', 'Technology', 'Robotics']);
  assert.deepEqual(saved.highlights.map(({ text, note }) => ({ text, note })), [{ text: 'A key passage.', note: 'Why it matters' }]);
  const row = $('items').querySelector('tr');
  assert.deepEqual([...row.querySelectorAll('.tag')].map(tag => tag.textContent), ['AI', 'Technology', 'Robotics']);
  assert.equal(row.querySelector('.item-note').textContent, 'Read before the meetup');
  row.querySelector('.note-chip').click();
  assert.ok($('note-dialog').open, 'the Note marker opens the full note');
  assert.equal($('note-text').textContent, 'Read before the meetup');
  $('note-edit').click();
  assert.ok($('editor').open && !$('note-dialog').open);
  assert.equal($('edit-note').value, 'Read before the meetup');
  $('editor').close();
  const robotics = [...document.querySelectorAll('#tag-list .folder-link')].find(link => link.title === 'Robotics');
  assert.equal(robotics.querySelector('.count').textContent, '1');
  robotics.click();
  assert.equal($('page-title').textContent, 'Robotics');
  assert.equal($('items').children.length, 1);
  $('sidebar-add-tag').click();
  assert.ok($('tag-dialog').open);
  $('tag-name').value = 'Cooking';
  $('tag-form').dispatchEvent(new dom.window.SubmitEvent('submit', { cancelable: true, submitter: $('tag-form').querySelector('[type=submit]') }));
  await settle();
  assert.ok(!$('tag-dialog').open);
  assert.ok([...document.querySelectorAll('#tag-list .folder-link')].some(link => link.title === 'Cooking'), 'the new tag is listed');
  $('all-bookmarks').click();
  $('search').value = 'meetup'; $('search').dispatchEvent(new dom.window.Event('input'));
  await new Promise(resolve => setTimeout(resolve, 150));
  assert.equal($('items').children.length, 1, 'search matches notes');
  $('search').value = ''; $('search').dispatchEvent(new dom.window.Event('input'));
  await new Promise(resolve => setTimeout(resolve, 150));
  $('new-bookmark').click();
  $('edit-name').value = 'Post on X'; $('edit-url').value = 'https://x.com/jack/status/20';
  submit(); await settle();
  assert.equal(document.querySelectorAll('iframe').length, 0, 'the list view does not contact X');
  $('gallery-view').click();
  const frames = [...document.querySelectorAll('iframe.tweet-embed')];
  assert.equal(frames.length, 1);
  assert.equal(frames[0].src, 'https://platform.twitter.com/embed/Tweet.html?id=20&dnt=true');
  $('list-view').click();
  await new Promise(resolve => setTimeout(resolve, 6100));
  dom.window.close();
});

test('a highlights label opens the list of highlights, where each can be deleted', async () => {
  const dom = new JSDOM(await readFile(new URL('../manager.html', import.meta.url), 'utf8'), { url: 'https://extension.local/manager.html' });
  globalThis.document = dom.window.document;
  globalThis.DOMParser = dom.window.DOMParser;
  const $ = id => document.getElementById(id);
  dom.window.HTMLDialogElement.prototype.showModal = function () { this.setAttribute('open', ''); };
  dom.window.HTMLDialogElement.prototype.close = function () { this.removeAttribute('open'); this.dispatchEvent(new dom.window.Event('close')); };
  const highlights = [{ id: 'h1', text: 'First passage', note: 'Why', createdAt: Date.now() }, { id: 'h2', text: 'Second passage', createdAt: Date.now() }];
  const mock = fixture({ id: 'root________', children: [{ id: 'unfiled_____', parentId: 'root________', title: 'Other Bookmarks', children: [
    { id: 'a', parentId: 'unfiled_____', title: 'Essay', url: 'https://example.com/', type: 'bookmark', highlights }
  ] }] });
  globalThis.browser = mock.api;
  Object.defineProperty(globalThis.navigator, 'locks', { value: mock.locks, configurable: true });
  await import('../manager.js?highlights');
  const settle = () => new Promise(resolve => setTimeout(resolve, 10));
  await settle();
  const chip = () => document.querySelector('#items .highlight-chip');
  assert.equal(chip().textContent, '2 highlights');
  chip().click();
  assert.ok($('highlights-dialog').open);
  assert.deepEqual([...$('highlights-list').querySelectorAll('.quote')].map(quote => quote.textContent), ['First passage', 'Second passage']);
  assert.equal($('highlights-list').querySelector('.highlight-note').textContent, 'Why');
  $('highlights-list').querySelector('.item-action').click(); await settle();
  assert.equal(chip().textContent, '1 highlight');
  assert.deepEqual([...$('highlights-list').querySelectorAll('.quote')].map(quote => quote.textContent), ['Second passage']);
  $('highlights-list').querySelector('.item-action').click(); await settle();
  assert.equal(chip(), null);
  assert.ok(!$('highlights-dialog').open, 'the list closes when its last highlight is deleted');
  $('search').value = 'second'; $('search').dispatchEvent(new dom.window.Event('input'));
  await new Promise(resolve => setTimeout(resolve, 150));
  assert.equal($('items').children.length, 0, 'deleted highlights are no longer searchable');
  dom.window.close();
});
